# Generated by Django 6.0.1 on 2026-01-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategori',
            table='renpwn_kategori',
        ),
        migrations.AlterModelTable(
            name='produk',
            table='renpwn_produk',
        ),
        migrations.AlterModelTable(
            name='status',
            table='renpwn_status',
        ),
    ]
